# Generated by Django 2.1.1 on 2018-09-26 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('count', models.IntegerField(default=1, verbose_name='商品数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('comment', models.CharField(max_length=256, verbose_name='商品评论')),
            ],
            options={
                'verbose_name': '订单商品信息',
                'verbose_name_plural': '订单商品信息',
                'db_table': 'Order_goods',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('order_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='订单ID')),
                ('pay_method', models.SmallIntegerField(choices=[(0, '货到付款'), (1, '微信支付'), (2, '支付宝'), (3, '银联支付')], default=0, verbose_name='付款方式')),
                ('order_status', models.SmallIntegerField(choices=[(0, '待付款'), (1, '待发货'), (2, '待收货'), (3, '待评价'), (4, '已完成')], default=0, verbose_name='订单状态')),
                ('total_count', models.IntegerField(default=1, verbose_name='订单数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('express_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='运费')),
                ('trade_id', models.CharField(max_length=128, verbose_name='交易编号')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Address', verbose_name='订单地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='下单用户')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
                'db_table': 'Order_info',
            },
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderInfo', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSKU', verbose_name='商品'),
        ),
    ]
